START TRANSACTION;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS package;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS developer;
DROP TABLE IF EXISTS open_source;
DROP TABLE IF EXISTS proprietary;
DROP TABLE IF EXISTS provider;
DROP TABLE IF EXISTS repository;
DROP TABLE IF EXISTS mirror;
DROP TABLE IF EXISTS provider_hosts_mirror;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS issue;
DROP TABLE IF EXISTS feature_request;
DROP TABLE IF EXISTS bug_report;
DROP TABLE IF EXISTS replies_to;
DROP TABLE IF EXISTS version;
DROP TABLE IF EXISTS package_has_version;
DROP TABLE IF EXISTS depends_on;
DROP TABLE IF EXISTS version_contains_issue;
DROP TABLE IF EXISTS vendor;
DROP TABLE IF EXISTS vendor_owns_package;
DROP TABLE IF EXISTS developer_works_on_package;
DROP TABLE IF EXISTS package_has_review;
DROP TABLE IF EXISTS repository_serves_mirror;
DROP TABLE IF EXISTS docu_author;
DROP TABLE IF EXISTS documentation;
DROP TABLE IF EXISTS localisation;
DROP TABLE IF EXISTS version_has_loc_doc;
DROP TABLE IF EXISTS user_replies_to_issue;
DROP TABLE IF EXISTS provider_hosts_mirror;
SET FOREIGN_KEY_CHECKS = 1;
COMMIT;
